'use strict';let token=null,rows=[],dirty=false;const el=id=>document.getElementById(id),status=t=>el('status').textContent=t;
function safeImage(v){try{return new URL(v).protocol==='https:'}catch{return false}}
async function load(){rows=await catalogRequest('/rest/v1/products?select=*&order=created_at.desc',{},token);el('list').replaceChildren();for(const p of rows){const div=document.createElement('div');div.className='row';const img=document.createElement('img');if(safeImage(p.image))img.src=p.image;img.alt=p.name;const text=document.createElement('div');const name=document.createElement('strong');name.textContent=p.name;const sub=document.createElement('div');sub.className='muted';sub.textContent=`${p.units} × ${p.weight} · ${p.published?'Publicerad':'Utkast'}`;text.append(name,sub);const b=document.createElement('button');b.textContent='Redigera';b.onclick=()=>{if(dirty&&!confirm('Lämna osparade ändringar?'))return;fill(p)};div.append(img,text,b);el('list').append(div)}}
function fill(p={}){for(const key of ['id','name','brand','description','weight','units','price','image'])el(key).value=p[key]??'';el('published').checked=p.published??false;el('file').value='';el('form-title').textContent=p.id?'Redigera produkt':'Ny produkt';el('preview').hidden=!safeImage(p.image);if(safeImage(p.image))el('preview').src=p.image;dirty=false}
el('login').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const session=await catalogRequest('/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:el('email').value,password:el('password').value})});token=session.access_token;const editors=await catalogRequest('/rest/v1/catalog_editors?select=user_id',{},token);if(!editors.length){await catalogRequest('/auth/v1/logout',{method:'POST'},token);token=null;throw new Error('Kontot har inte behörighet att redigera produkter.')}el('password').value='';await load();await loadPromos();el('login').hidden=true;el('workspace').hidden=false;status('Inloggad. Ändringar sparas gemensamt och visas på webbplatsen när produkten är publicerad.')}catch(err){status(err.message)}finally{b.disabled=false}};
el('edit').oninput=()=>dirty=true;
el('edit').onsubmit=async e=>{e.preventDefault();el('save').disabled=true;status('Sparar…');try{let image=el('image').value.trim();const file=el('file').files[0];if(file){if(file.size>5242880||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Välj JPG, PNG eller WebP under 5 MB.');const path=crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);await catalogRequest('/storage/v1/object/product-images/'+path,{method:'POST',headers:{'Content-Type':file.type},body:file},token);image=CATALOG_URL+'/storage/v1/object/public/product-images/'+path;el('image').value=image;el('file').value=''}if(image&&!safeImage(image))throw new Error('Bilden måste ha en HTTPS-adress.');if(el('published').checked&&!image)throw new Error('Lägg till en bild innan publicering.');const data={name:el('name').value.trim(),brand:el('brand').value.trim(),description:el('description').value.trim(),weight:el('weight').value.trim(),units:Number(el('units').value),price:el('price').value===''?null:Number(el('price').value),image,published:el('published').checked};if(!data.name||!data.brand||!data.weight)throw new Error('Fyll i namn, varumärke och vikt.');const id=el('id').value;const saved=await catalogRequest('/rest/v1/products'+(id?'?id=eq.'+encodeURIComponent(id):''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(data)},token);if(!saved.length)throw new Error('Produkten sparades inte. Kontrollera behörigheten.');fill(saved[0]);await load();status('Sparat. '+(data.published?'Produkten visas när webbplatsen laddas om.':'Produkten är ett dolt utkast.'))}catch(err){status('Kunde inte spara: '+err.message)}finally{el('save').disabled=false}};
for(const id of ['new','cancel'])el(id).onclick=()=>{if(!dirty||confirm('Lämna osparade ändringar?'))fill()};el('logout').onclick=async()=>{if(dirty&&!confirm('Logga ut utan att spara?'))return;try{await catalogRequest('/auth/v1/logout',{method:'POST'},token)}catch{}token=null;rows=[];fill();el('list').replaceChildren();el('workspace').hidden=true;el('login').hidden=false;status('Utloggad.')};el('export').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));a.href=u;a.download='saba-food-produkter.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

let promoDirty=false;
function fillPromo(p={}){for(const k of ['id','supplier','title','description','image','link','button_text','position'])el('promo-'+k).value=p[k]??(k==='position'?0:k==='button_text'?'Läs mer':'');for(const k of ['published','sponsored'])el('promo-'+k).checked=!!p[k];el('promo-file').value='';el('promo-form-title').textContent=p.id?'Redigera yta':'Ny yta';promoDirty=false}
async function loadPromos(){const promos=await catalogRequest('/rest/v1/promotions?select=*&order=position.asc,created_at.desc',{},token);el('promo-list').replaceChildren();if(!promos.length)el('promo-list').textContent='Inga ytor ännu. Lägg till din första.';for(const p of promos){const row=document.createElement('div');row.className='row';const text=document.createElement('span');text.textContent=p.title+' · '+(p.published?'Publicerad':'Utkast');const b=document.createElement('button');b.type='button';b.textContent='Redigera';b.onclick=()=>{if(!promoDirty||confirm('Lämna osparade ändringar?'))fillPromo(p)};row.append(text,b);el('promo-list').append(row)}}
el('promo-new').onclick=()=>{if(!promoDirty||confirm('Lämna osparade ändringar?'))fillPromo()};
el('promo-edit').oninput=()=>promoDirty=true;
el('promo-edit').onsubmit=async e=>{e.preventDefault();el('promo-save').disabled=true;status('Sparar yta…');try{let image=el('promo-image').value.trim();const file=el('promo-file').files[0];if(file){if(file.size>5242880||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Välj JPG, PNG eller WebP under 5 MB.');const path=crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);await catalogRequest('/storage/v1/object/product-images/'+path,{method:'POST',headers:{'Content-Type':file.type},body:file},token);image=CATALOG_URL+'/storage/v1/object/public/product-images/'+path;el('promo-image').value=image;el('promo-file').value=''}if(!safeImage(image))throw new Error('Lägg till en bild med HTTPS-adress.');const data={image};for(const k of ['supplier','title','description','link','button_text'])data[k]=el('promo-'+k).value.trim();if(!data.title||!data.supplier)throw new Error('Fyll i leverantör och rubrik.');if(data.link&&!safeImage(data.link))throw new Error('Länken måste börja med HTTPS.');data.position=Number(el('promo-position').value);for(const k of ['published','sponsored'])data[k]=el('promo-'+k).checked;const id=el('promo-id').value;const saved=await catalogRequest('/rest/v1/promotions'+(id?'?id=eq.'+encodeURIComponent(id):''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(data)},token);if(!saved.length)throw new Error('Ytan sparades inte.');fillPromo(saved[0]);await loadPromos();status(data.published?'Sparat. Ytan visas när webbplatsen laddas om.':'Sparat som dolt utkast.')}catch(err){status('Kunde inte spara: '+err.message)}finally{el('promo-save').disabled=false}};
addEventListener('beforeunload',e=>{if(promoDirty){e.preventDefault();e.returnValue=''}});
const productLogout=el('logout').onclick;el('logout').onclick=async()=>{if(promoDirty&&!confirm('Logga ut utan att spara ytan?'))return;await productLogout();if(!token){fillPromo();el('promo-list').replaceChildren()}};
