const SITE_FIELDS=[
 ['site_logo','Webbplatsens logotyp (HTTPS)','header > a:first-child img','image'],
 ['hero_title','Huvudrubrik','.hero-copy h1'],['hero_text','Introduktion','.hero-copy p'],['hero_image','Huvudbild (HTTPS)','.landscape','image'],
 ['about_title','Om oss – rubrik','.company-body h2'],['about_text','Om oss – beskrivning','.company-body p'],['about_extra','Om oss – extra text','.company-body p:nth-of-type(2)'],
 ['delivery_title','Leverans – rubrik','.delivery-section h2'],['delivery_text','Leverans – beskrivning','.delivery-section p'],['delivery_terms','Leverans – villkor','.delivery-section p:nth-of-type(2)'],
 ['supplier_title','Leverantörer – rubrik','#suppliers-title'],['supplier_intro','Leverantörer – introduktion','.supplier-intro p'],
 ['contact_title','Kontakt – rubrik','.contact-section h2'],['contact_intro','Kontakt – introduktion','.section-heading > p'],
 ['person1_name','Kontakt 1 – namn','.person:nth-child(1) h3'],['person1_role','Kontakt 1 – roll','.person:nth-child(1) p'],['person1_phone','Kontakt 1 – telefon','.person:nth-child(1) a','phone'],['person1_image','Kontakt 1 – bild (HTTPS)','.person:nth-child(1) img','image'],
 ['person2_name','Kontakt 2 – namn','.person:nth-child(2) h3'],['person2_role','Kontakt 2 – roll','.person:nth-child(2) p'],['person2_phone','Kontakt 2 – telefon','.person:nth-child(2) a','phone'],['person2_image','Kontakt 2 – bild (HTTPS)','.person:nth-child(2) img','image'],
 ['address','Besöksadress (en rad per del)','.address address','address'],['email','Kontaktmejl','.address a[href^="mailto:"]','email'],
 ['hours_week','Öppettider måndag–fredag','.address dl div:nth-child(1) dd'],['hours_sat','Öppettider lördag','.address dl div:nth-child(2) dd'],['hours_sun','Öppettider söndag','.address dl div:nth-child(3) dd']
];
function applySiteSettings(values){for(const [key,label,selector,type] of SITE_FIELDS){const value=values[key];if(typeof value!=='string')continue;const node=document.querySelector(selector);if(!node)continue;if(type==='image'){if(value.startsWith('https://'))node.src=value;continue}node.textContent=value;node.style.whiteSpace='pre-line';if(type==='phone'){const old=node.getAttribute('href');for(const a of document.querySelectorAll('a[href^="tel:"]'))if(a.getAttribute('href')===old){a.href='tel:'+value.replace(/[^+\d]/g,'');if(a.closest('.person'))a.textContent=value;}}if(type==='email'){for(const a of document.querySelectorAll('a[href^="mailto:"]')){a.href='mailto:'+value;a.textContent=value}}if(type==='address'){const query=encodeURIComponent(value);document.querySelector('.location iframe').src='https://maps.google.com/maps?q='+query+'&z=15&output=embed';document.querySelector('.address a[target="_blank"]').href='https://www.google.com/maps/search/?api=1&query='+query}}}
async function loadSiteContent(){try{const rows=await catalogRequest('/rest/v1/site_content?select=key,value');for(const row of rows){if(row.key==='settings')applySiteSettings(row.value);if(row.key==='suppliers'){const section=document.querySelector('#leverantorer');section.querySelectorAll('.supplier-card').forEach(n=>n.remove());const list=row.value.items.filter(p=>p.published).sort((a,b)=>a.position-b.position);section.hidden=!list.length;for(const p of list){const card=document.createElement('article');card.className='supplier-card';const logo=document.createElement('div');logo.className='supplier-logo';const img=document.createElement('img');img.alt=p.name;img.loading='lazy';if(p.image.startsWith('https://'))img.src=p.image;logo.append(img);const body=document.createElement('div');const h=document.createElement('h3');h.textContent=p.name;const desc=document.createElement('p');desc.textContent=p.description;body.append(h,desc);card.append(logo,body);if(p.link.startsWith('https://')){const a=document.createElement('a');a.className='supplier-link';a.href=p.link;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Besök '+p.name;card.append(a)}section.append(card)}}}}catch{ /* Keep the existing content when the service is unavailable. */ }}
if(document.querySelector('#leverantorer'))loadSiteContent();
