let contentDirty=false,supplierItems=[],contentVersion={};
async function readContent(){const rows=await catalogRequest('/rest/v1/site_content?select=*',{},token);return Object.fromEntries(rows.map(r=>[r.key,r]))}
async function saveContent(key,value){const previous=contentVersion[key];const result=await catalogRequest('/rest/v1/site_content'+(previous?'?key=eq.'+key+'&updated_at=eq.'+encodeURIComponent(previous):''),{method:previous?'PATCH':'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(previous?{value}:{key,value})},token);if(!result.length)throw Error('Innehållet har ändrats i en annan session. Ladda om innan du sparar.');contentVersion[key]=result[0].updated_at}
async function loadContentAdmin(){const data=await readContent();contentVersion=Object.fromEntries(Object.entries(data).map(([k,r])=>[k,r.updated_at]));supplierItems=data.suppliers?.value.items||[];renderSuppliersAdmin();const html=await (await fetch('index.html')).text();const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('br').forEach(n=>n.replaceWith('\n'));const fields=el('settings-fields');fields.replaceChildren();for(const [key,label,selector,type] of SITE_FIELDS){const wrap=document.createElement('div'),l=document.createElement('label'),input=document.createElement(type==='image'||type==='email'||type==='phone'?'input':'textarea');input.id='setting-'+key;l.htmlFor=input.id;l.textContent=label;const node=doc.querySelector(selector);input.value=data.settings?.value[key]??(type==='image'?new URL(node.getAttribute('src'),location.href).href:node?.innerText||node?.textContent||'');input.maxLength=2000;if(type==='email')input.type='email';if(type==='image')input.type='url';wrap.append(l,input);if(type==='image'){const file=document.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.id='setting-file-'+key;file.setAttribute('aria-label',label+' – ladda upp');wrap.append(file)}fields.append(wrap)}contentDirty=false}
function renderSuppliersAdmin(){el('supplier-list').replaceChildren();for(const p of [...supplierItems].sort((a,b)=>a.position-b.position)){const row=document.createElement('div');row.className='row';const name=document.createElement('span');name.textContent=p.name+' · '+(p.published?'Publicerad':'Dold');const button=document.createElement('button');button.textContent='Redigera';button.type='button';button.onclick=()=>{if(!contentDirty||confirm('Lämna osparade ändringar?'))fillSupplier(p)};row.append(name,button);el('supplier-list').append(row)}}
function fillSupplier(p={}){for(const k of ['id','name','description','image','link','position'])el('supplier-'+k).value=p[k]??(k==='position'?0:'');el('supplier-published').checked=!!p.published;el('supplier-file').value='';contentDirty=false}
async function uploadContent(file){if(file.size>5242880||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Välj JPG, PNG eller WebP under 5 MB.');const path=crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);await catalogRequest('/storage/v1/object/product-images/'+path,{method:'POST',headers:{'Content-Type':file.type},body:file},token);return CATALOG_URL+'/storage/v1/object/public/product-images/'+path}
el('supplier-new').onclick=()=>{if(!contentDirty||confirm('Lämna osparade ändringar?'))fillSupplier()};
el('supplier-edit').oninput=el('settings-edit').oninput=()=>contentDirty=true;
el('supplier-edit').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const p={id:el('supplier-id').value||crypto.randomUUID()};for(const k of ['name','description','image','link'])p[k]=el('supplier-'+k).value.trim();const file=el('supplier-file').files[0];if(file){p.image=await uploadContent(file);el('supplier-image').value=p.image;el('supplier-file').value=''}if(!p.name||!safeImage(p.image)||(p.link&&!safeImage(p.link)))throw Error('Fyll i namn och en HTTPS-bild. Länken måste också använda HTTPS.');p.position=Number(el('supplier-position').value);p.published=el('supplier-published').checked;const next=[...supplierItems.filter(x=>x.id!==p.id),p];await saveContent('suppliers',{items:next});supplierItems=next;fillSupplier(p);renderSuppliersAdmin();status('Leverantören sparad. Ladda om webbplatsen för att se ändringen.')}catch(err){status(err.message)}finally{e.submitter.disabled=false}};
el('settings-edit').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const values={};for(const [key,label,selector,type] of SITE_FIELDS){const file=el('setting-file-'+key)?.files[0];if(file){el('setting-'+key).value=await uploadContent(file);el('setting-file-'+key).value=''}const v=el('setting-'+key).value.trim();if(type==='image'&&!safeImage(v))throw Error(label+': använd HTTPS.');values[key]=v}await saveContent('settings',values);contentDirty=false;status('Webbplatsens innehåll sparat. Ladda om webbplatsen för att se ändringarna.')}catch(err){status(err.message)}finally{e.submitter.disabled=false}};
addEventListener('beforeunload',e=>{if(contentDirty){e.preventDefault();e.returnValue=''}});
const previousLogout=el('logout').onclick;el('logout').onclick=async()=>{if(contentDirty&&!confirm('Logga ut utan att spara innehållet?'))return;await previousLogout();if(!token){supplierItems=[];contentVersion={};contentDirty=false;el('settings-fields').replaceChildren();el('supplier-list').replaceChildren()}};
